### ISSUE TITLE
Update filesystem structure

### ISSUE THREAD

**Issue by kddrake** [Jropp/jason-ropp-js-iobp#18]
# Please complete these issues before attempting this issue
- [x] #20

## Main Goal
Ensure your project structure aligns with Banno's general filesystem structure as you continue to build it

### When Accomplished
- [x] Project file structure follows [our code style guide](https://docs.banno.com/ux/CodeStyle/#filesystem-structure)

## Notes
- This should be done in tandem with #27 
- You may run into the [ways of old](https://docs.banno.com/ux/ProjectPractices/#file-organization) while looking through documentation. Don't bother with it.

**Comment by Jropp** [comment]
#33 commit addresses this

**Comment by Jropp** [comment]
@kddrake John Papa's structure in the documentation is based on Angular. 

## Note

These remarks are being worked out in the `router` branch, not the #20 PR. 

## Questions

In platform-ux there is a `src/components/feature` structure, should I follow that for my components?

My project also has (for example) an add-users.html file that serves as the add-users page. I then put an add-user component in that file. Should these parent pages be in their own separate `src/pages` folder? Or should I put them in the root?

**Comment by kddrake** [comment]
> John Papa's structure in the documentation is based on Angular.

Yupp... that's why I mentioned not to bother with it (_see the second bullet in the Notes section_)

> In platform-ux there is a src/components/feature structure, should I follow that for my components?

Nope, not quite. I don't think your project will end up being big enough to necessitate a `components` folder. You should be fine to follow the our styleguide (_see the link in the Accomplished section_) pretty much to a "t".

> Should these parent pages be in their own separate src/pages folder? Or should I put them in the root?

These will go away. Don't worry about their placement for now.

**Comment by kddrake** [comment]
closed in #40
