### ISSUE TITLE
Create and serve index.html

### ISSUE THREAD

**Issue by kddrake** [Jropp/jason-ropp-js-iobp#28]
## Main Goal
Have your app default an actual webpage

### When Accomplished
- [x] Hitting `...:1820/` loads `index.html` rather than the directory itself
- [x] `index.html` *at very least* contains the ability to navigation to each view
- [x] Navigation *to* any view *from* any view is possible in app

### Notes
- Other than navigation, I don't care what your "home page" shows. You can make something up or choose a view you've already made.
- This is something I spaced on that should have been done when you initially set up the server (#4). My bad.

**Comment by Jropp** [comment]
PR #29 fixes this
