### ISSUE TITLE
Use polymer-webpack-plugin

### ISSUE THREAD

**Issue by Jropp** [Jropp/jason-ropp-js-iobp#38]
# Please complete these issues before attempting this issue
- [ ] #35 

## Main Goal
The goal is to bundle polymer component elements using [polymer-webpack-loader](https://github.com/webpack-contrib/polymer-webpack-loader)

### When Accomplished
- [ ] component files should be converted to js files and bundled? 
- [ ] page should display and function appropriately, save new users, delete users, navigate pages, etc.
- [ ] page should display and function properly on Firefox and safari

## Notes

[Chad Killingsworth talk at Polymer Summit](https://www.youtube.com/watch?v=LpMI_Do5t5U)
[Rob Dodson Blog](http://robdodson.me/how-to-use-polymer-with-webpack/)
[npm](https://www.npmjs.com/package/polymer-webpack-loaderl)

### Dependencies
- [ ] #35 

## Success

- [ ] Polymer-webpack-plugin installed and running properly
- [ ] Styles.css connected to polymer components
- [ ] Works on Chrome
- [ ] Works on F*#%fox
- [ ] Works on Safari

**Comment by kddrake** [comment]
Also I'm _pretty sure_ this will solve your problem with the nav component not showing up in Firefox. Don't quote me though.

**Comment by Jropp** [comment]
# NOTE OF GREAT IMPORTANCE!!!!!!!!!!!!!

- [This line in index.ejs had an "!" and shouldn't have](https://github.com/Jropp/jason-ropp-js-iobp/blob/pol-wp/src/index.ejs#L29)

- I don't know if it was necessary or not, but instead of <import> statements at the top of nav-bar and user-component I put [import statements](https://github.com/Jropp/jason-ropp-js-iobp/blob/pol-wp/src/user-component/user-component.html#L89) in the script of those components.
