### ISSUE TITLE
Update nav component

### ISSUE THREAD

**Issue by kddrake** [Jropp/jason-ropp-js-iobp#39]
# Please complete these issues before attempting this issue
- [ ] #30 
- [ ] #31 
- [ ] #32 
...

## Main Goal
Update your navigation component ~so that it functions _something like_ router~ and turn your app into a single-page app.

### When Accomplished
- [ ] App functions and navigates as it did before, just without page loads
- [ ] Navigation functions properly in Firefox

## Notes
_Still working through what I want to see from this... stay tuned._

### Dependencies
#30 
#32 
...

**Comment by Jropp** [comment]
@kddrake the router branch

**Comment by kddrake** [comment]
@Jropp mmm you can build off of that one eventually if you'd like but that's not quite what I'll want. I'm updating the issue currently. I don't think you'll be able to go about it the way I'd like you to until you've knocked out a few other issues.

**Comment by Jropp** [comment]
@kddrake gotcha

**Comment by kddrake** [comment]
this no longer applies to the project. closing.
