### ISSUE TITLE
Add linter to project

### ISSUE THREAD

**Issue by kddrake** [Jropp/jason-ropp-js-iobp#8]
## Main Goal
Add a linter to your project so that you don't accumulate hours looking for "the spot you forgot that last `)`"

### When Accomplished
- [x] Running `npm start` runs a linter on your javascript **before** serving files
- [x] The linters reports issues when found
  - [x] The reports are formatted decently

## Notes
- Linting is a weird way of saying "identify and report on patterns". Linters essentially make it easier to catch syntax mistakes and when breaking best practice. There are a lot out there, but I would suggest sticking with something our products at Banno use.

## Dependencies
- [x] #5

**Comment by Jropp** [comment]
## Issue:

Addressing this in #21 

I currently have the linter setup and working. I've also placed it in npm start along with the server, but they aren't playing nice together. As in the linter doesn't work with the server like it does on its own:

```
"scripts": {
    "build": "",
    "start": "npm run lint | python -m SimpleHTTPServer 1820",
    "help": "npm-scripts-help",
    "lint":  "ux-lint --fix src/*.js"
  },
```
